AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data ingestion for forecastflow
# for local testing
# Parameters:
#   ApiKey:
#     Type: String
#     Default: default value
#   ApiHost:
#     Type: String
#     Default: default value
Resources:
  DestinationBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "forecast-flow-ingestion-main"

  ForecastFlowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ForecastFlowIngestFunction
      CodeUri: ingest_function/
      Handler: get_data.lambda_handler
      Runtime: python3.9
      Timeout: 600
      Architectures:
      - x86_64
      # for local testing 
      # Environment:
      #   Variables:
      #     API_KEY: 
      #       Ref: ApiKey
      #     API_HOST: 
      #       Ref: ApiHost
      Policies:
        - S3CrudPolicy:
            BucketName: "forecast-flow-ingestion-main"
      # Events:
      #   DailySchedule:
      #     Type: Schedule
      #     Properties:
      #       Schedule: '@daily'
  
          
