name: Deploy and Invoke ForecastFlowIngestFunction
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::928389782162:role/github-actions-role
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 01_ingestion_pipeline/get_data/requirements.txt

      - name: Build and Deploy SAM App
        run: |
          cd 01_ingestion_pipeline
          sam build
          sam deploy

      - name: Invoke Lambda function
        run: |
          keysecret=${{ secrets.key }}
          hostsecret=${{ secrets.host }}
          payload=`echo "{\"KEY\": \"$keysecret\", \"HOST\": \"$hostsecret\"}" | openssl base64`
          aws lambda invoke --function-name ForecastFlowIngestFunction --payload "$payload" -
